version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errorlint
    - wrapcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gosec
    - unconvert
    - unparam

  settings:
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true

    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
      ignore-package-globs:
        - github.com/tolmachov/mcp-telegram/*

    gosec:
      excludes:
        - G104

    misspell:
      locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0